Adding tasks analysis content
Interacao-Humano-Computador/2020.1-SEI pull request #41
Opened 2020-09-26 03:41 UTC by zarbielli

## Descrição

Documento de Análise de Tarefas

## Resolve (Issues)

#35 

## Tarefas gerais realizadas

- Análise de tarefas do site
- Documentação da análise

2020-09-26 15:22 UTC, KiSobral requested changes
O conteúdo ficou muito bom :smile: 

Precisa de algumas mudanças ortográficas, que são de simples ajuste.

Já a referência precisa ser incluída antes do documento ser merjado

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +Análise de como uma tarefa é exercida, compreendendo de uma descrição detalhada tanto de atividades físicas como mentais, duração da tarefa, frequência da tarefa, alocação da tarefa, complexidade da
retirar o "de" em "compreendendo de uma", a ficar "compreendendo uma ..."

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +Com esse aspecto pretendemos melhorar a distribuição de botões e icones da página que são contra-intuitivos, por exemplo o botão do menu que não fica próximo ao menu. É necessário tambem mudar os ico
Adicionar o acento agudo na palavra "ícone".

trocar o uso da palavra "por" por "colocar" ou então "inserir".

acentuar a palavra "coloca-los", a ficar "colocá-los"

ajeitar a palavra "confirmidade" por "conformidade"

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +Nesse princípio é levantada a importancia de existir retornos do sistema as ações do usuário para assim tirar qualquer incerteza do estado do sistema que pode existir ao usuário executar uma ação. A
Pontuar a palavra importância

pontuar o seguinte trecho "... sistema as ações ..." a ficar "... sistemas às ações ..."

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +Com essse princípio em mente foram analisadas as respostas do site, que performou bem, quase todas as ações do usuário no site que necessitam de retorno o possuem, porem é necessário deixar os retorn
Reformular o trecho ".. do site, que performou bem, quase todas as ..." para "... do site, que performou bem em quase todas as ..."

Reformular o trecho ".. e portanto necessário a interação do usuário..." para "... portanto é necessário a interação do usuário ..."

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +Como o site tem poucas opções fica bem evidenciado as opções corretas, atraves do menu e de boas descrições para as abas. O sistema tambem não permite fazer ações que o usuário não pode, tirando do e
pontuar a palavra "tambem" a ficar "também".

pontuar a palavra "porem" a ficar "porém" (é preciso trocar as outras escritas dessa palavra sem acento, um ctrl F ajuda bastante nessa tarefa)

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +Mapeamento se diz em relção a manipulação dos controles serem adequadas, de um jeito que o usuário consiga entender o que uma coisa faz. Muito utilizado para descrever essas ações de um jeito simples
acentuar a palavra "simbolos" a ficar "símbolos"

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +Nesse ponto o site possuem poucas coisa que necessitam de mudança, a grande maioria dos botões possuem legendas ou placeholders e icones significativos, ficando portanto atacar esses poucos pontos de
trocar a concordância de "nesse ponto o site possuem" para "nesse ponto o site possui poucas coisas que necessitem"

2020-09-26 15:22 UTC, KiSobral commented on docs/use_context/tasks_analysis.md
> +
É preciso adicionar as referências que você usou para construir esse documento. Dá uma olhada nos outros documentos para ter uma noção de como as referências estão sendo escritas na wiki.

2020-09-27 02:06 UTC, LeoSilvaGomes reviewed
Está bem bom, **parabéns!** :tada: só corrigir os errinhos que eu e o Hugo comentamos

2020-09-27 02:06 UTC, LeoSilvaGomes commented on docs/use_context/tasks_analysis.md
> +Mapeamento se diz em relção a manipulação dos controles serem adequadas, de um jeito que o usuário consiga entender o que uma coisa faz. Muito utilizado para descrever essas ações de um jeito simples
trocar a palavra "relção" por "relação

2020-09-28 23:31 UTC, merged