[WIP] #20 Resultado e entrevistas da analise de tarefas
Interacao-Humano-Computador/2020.1-SEI pull request #63
Opened 2020-11-03 21:54 UTC by LeoSilvaGomes

## Resultado e entrevistas da analise de tarefas

Descrição concisa do que foi feito

## Resolve (#20)

Issues que foram resolvidas com o PR

## Tarefas gerais realizadas

- Descrever acontecimento na 1º entrevista
- Descrever acontecimento na 2º entrevista
- Descrever acontecimento na 3º entrevista
- Fazer conclusão a partir das opiniões feitas pelos entrevistados

2020-11-04 02:02 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/interviews.md
> +[3:26] Victor identificar facilmente onde precisa clicar para iniciar um novo processo, sem nenhuma dificuldade para encontrar os tipos de processo que estão listados ao final da página.
Trocar "Victor identificar" por "Victor identifica"

2020-11-04 02:09 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/interviews.md
> +[6:20] Na parte de avaliação dos filtro que a página disponibiliza, Victor inicia falando que não sabe o que seria um recibo eletrônico, deixando a entender que poderia prejudicá-lo na experiência co
* Colocar a palavra **filtro** no plural no trecho _"Na parte de avaliação dos filtro que a página disponibiliza,"_.
* Trocar a palavra **está** por **estar** no trecho _", e completa afirmando que imagina que os filtros parecem está completos."_.

2020-11-04 02:12 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/interviews.md
> +[10:15] Para finalizar é pedido que Victor execute o _logout_ no sistema, ela encontra com facilidade o botão na _topbar_.
Trocar **ela** por **ele**

2020-11-04 02:23 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/interviews.md
> +# Termo de consentimento
Esse título está correto?

2020-11-04 02:25 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/interviews.md
> +Para realização das entrevistas, se fez necessário a elaboração de um planejamento por parte da equipe, esse planejamento pode ser encontrado no [planejamento do tópico de análises de tarefas](./plan
Lembre de adicionar o documento ou corrigir a linkagem caso ele já exista.

2020-11-04 02:27 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/interviews.md
> +[2:00] Para acessar o site do SEI, Micaella pesquisa no google por "sei unb" e acessa o [portalsei.unb.br](portalsei.unb.br).
Ficou faltando a expressão http e o www na linkagem do portal sei.

2020-11-04 02:28 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/interviews.md
> +[2:25] Para realizar o login, Micaella acessa a aba "Usuário externo e aluno" do portalsei e é redirecionada para o [sei.unb.br](sei.unb.br), ela informa o email e a senha, realizando o login com suc
Adicionar o http aqui também

2020-11-04 02:32 UTC, VictorJorgeFGA requested changes
Gostei da forma como tudo foi descrito. Os _iframes_ ficaram bem dimensionados. Se tiver usado alguma referência, não esqueça de adicionar. No geral, ficou excelente!

2020-11-05 19:21 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[2:25] Para realizar o login, Micaella acessa a aba _Usuário externo e aluno_ do portalsei e é redirecionada para o [sei.unb.br](https://www.sei.unb.br), ela informa o email e a senha, realizando o l
Aqui você deixou o link do _SEI!_ que não dá pra entrar. Seria bom trocar pelo _link_ usável.

2020-11-05 19:35 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[4:33] Para conclusão do 1º fluxo que Micaella enfrentou, ele disse que foi tranquilo a tarefa, que "olhando direitinho" você pode encontrar o que precisa. Além disso, Micaella esclareceu uma de suas
Trocar **ele** por **ela** em _", ele disse que foi tranquilo a tarefa, que "olhando direitinho" você pode encontrar o que precisa."_. Sugiro também quebrar a segunda frase em [frases menores](https://portugues.dicaseexercicios.com.br/redacao-faca-frases-mais-curtas/). Não precisa levar muito a sério, mas isso era algo que eu ouvia bastante quando eu treinava redação.

2020-11-05 19:40 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[5:20] O entrevistador pede para retornar para a tela principal. A primeira atitude de Micaella é clicar com convicção na logo do SEI, mas nada acontece. Micaella segue a procura de onde ela poderia
* Colocar crase no trecho _"Micaella segue a procura de..."_.
* Conjugar o verbo **ocultar** no trecho _", o botão apenas ocultar a _sidebar_."_
* Novamente frase demasiadamente longa.

2020-11-05 19:49 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[6:30] Micaella diz que é claro a forma de pesquisar e filtrar os peticionamentos em andamento. Entretanto complementa falando que poderia ficar melhor se colocassem _Número do peticionamento_ no lug
* Fazer a concordância nominal em _"Micaella diz que é **claro** a forma de pesquisar"_ substituindo por _"Micaella diz que é **clara** a forma de pesquisar"_.
* Faltou vírgula depois de _entretanto_ no trecho _"Entretanto complementa falando..."_ e também o pronome **ela**, ficando _"Entretanto, **ela** complementa ..."_.

2020-11-05 19:50 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[7:18] Para acessar a aba de recibos eletrônicos, Micaella acha com facilidades a aba pedida clicando em _Recibos Eletrônicos de Protocolo_, que se encontra na _sidebar_.
Colocar a palavra _**facilidades**_ no singular.

2020-11-05 19:54 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[8:25] Micaella tenta encontrar seu perfil clicando no ícone de um boneco que se encontra na _topbar_, mas ao clicar ela não recebe resposta da plataforma. Após a primeira tentativa, Micaella acessa
Ficou faltando vírgula depois de _**funcionalidade**_ em: _"Para essa funcionalidade Micaella precisou da ajuda ..."_

2020-11-05 19:55 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[10:18] Para esse momento final da entrevista o entrevistador deixa a Micaella fazer qualquer comentário que ela ache necessário. Ela diz que chegar nas abas pedidas foi intuitivo, mas deveria haver
Ficou faltando vírgula depois de _**entrevista**_ em: _"Para esse momento final da entrevista o entrevistador ..."_

2020-11-05 19:59 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[1:57] Para acessar o SEI, Victor favoritava o link quando utilizava no estágio já que o uso era constante, mas para a UnB Victor ressalta que pesquisa "sei unb" em uma plataforma de pesquisa e encon
* Faltou vírgula depois de _**estágio**_ em: _"Victor favoritava o link quando utilizava no estágio já que o uso ..."_
* O _link_ pro _portalsei_ está quebrado.

2020-11-05 20:08 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[8:47] Para as considerações finais, o entrevistador deixa um espaço livre para o Victor comentar o que quiser da plataforma. Victor afirma que a plataforma é bem feita em questão de design, mas just
A segunda frase ficou um pouco extensa e confusa de se entender.

2020-11-05 20:10 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +A terceira entrevista dura cerca de 11 minutos e é feita com a Thais Araujo, que é entrevistada pelo Leonardo Gomes. Thais tem 24 anos e está cursando engenharia de software na universidade de brasíl
Capitalizar _Engenharia de Software_ e _Universidade de Brasília_.

2020-11-05 20:15 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[1:44] Para acessar a plataforma, Thais pesquisa no google por "sei unb", entra no [portalsei.unb.br](https://www.portalsei.unb.br) e acessa a aba _Usuário externo e aluno_ do portalsei e é redirecio
* Sugiro separar a sequência de fatos com vírgula. As conjunções "**e**" ficaram um pouco confusas.
* O link do _SEI!_ que funciona pra mim é [este](https://sei.unb.br/sei/controlador_externo.php?acao=usuario_externo_logar&acao_origem=usuario_externo_enviar_cadastro&id_orgao_acesso_externo=0)

2020-11-05 20:17 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[2:43] Para esse fluxo, Thais comentou que não achou muito bom o acesso ao SEI pois existe outra plataforma que confunde os alunos, essa plataforma tem o mesmo nome e o mesmo layout da página de logi
Seria uma boa colocar o link das duas plataformas

2020-11-05 20:19 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[4:11] Na parte de selecionar um tipo de peticionamento, Thais passa alguns segundos tentando entender a página e pergunta se é clicando na lista de tipos de peticionamento existente na parte inferio
Faltou espaço no início da última frase.

2020-11-05 20:20 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[4:39] Thais analisa a página em busca dos documentos necessários para realizar o peticionamento. Após alguns segundos Thais seleciona o link do documento principal que está na sessão _Documentos_. A
Faltou uma vírgula após _**segundos**_ em: _"Após alguns segundos Thais"_

2020-11-05 20:23 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +[7:28] Thais acessa a _aba de recibos eletronicos_ localiza na _sidebar_ do site. Ela analisa os campos existentes na página e conclui o entendimento de cada um dos campos deixando claro que eles est
Trocar a palavra _localiza_ por _localizada_ na primeira frase.

2020-11-05 20:27 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +A partir da análise das entrevistas, conseguimos concluir que os fluxos documentados na análise de tarefa condizem com o fluxo feito por usuários do SEI ao utilizar a plataforma, desta forma, não há
* Colocar **tarefa** no plural em: "análise de tarefa".
* Retirar o artigo **"o"** do trecho: "avaliadora, reanalisar **o** as tarefas que o SEI apresenta"

2020-11-05 20:28 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +Para exemplificar os problemas que foram relatados pelos entrevistados, se faz necessário a utilização de um gráfico que reunas todas os pontos importantes que servirá de insumo para a equipe.
Corrigir a palavra **"reunas"** e fazer a concordância nominal de **todas** em: _"um gráfico que reunas todas os pontos importantes"_

2020-11-05 20:30 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +|                 Fluxo                 |                                                                     Problemas                                                                     |
Não sei se é a melhor alternativa, mas acredito que colocar uma _tag_ de quebra de linha após cada problema de um fluxo possa melhorar a legibilidade da tabela como um todo.

2020-11-05 20:31 UTC, VictorJorgeFGA commented on docs/evaluation/task_analysis/results.md
> +## Históricos de versões
Histórico não deveria estar no singular?

2020-11-05 20:32 UTC, VictorJorgeFGA requested changes
Como dito antes, ficou muito bom. Parabéns. Basta considerar os pontos que destaquei que estará perfeito.

2020-11-06 02:40 UTC, LeoSilvaGomes commented on docs/evaluation/task_analysis/results.md
> +[2:25] Para realizar o login, Micaella acessa a aba _Usuário externo e aluno_ do portalsei e é redirecionada para o [sei.unb.br](https://www.sei.unb.br), ela informa o email e a senha, realizando o l
feito, coloquei https://sei.unb.br/sei/controlador_externo.php?acao=usuario_externo_logar&acao_origem=usuario_externo_logar&id_orgao_acesso_externo=0 esse link

2020-11-06 16:18 UTC, zarbielli reviewed
Concordo com os pontos levantados pelo Victor! Assim que todos eles forem arrumados o documento estará pronto para subir.

Excelente trabalho! 💯

2020-11-06 23:42 UTC, LeoSilvaGomes commented on docs/evaluation/task_analysis/results.md
> +[6:30] Micaella diz que é claro a forma de pesquisar e filtrar os peticionamentos em andamento. Entretanto complementa falando que poderia ficar melhor se colocassem _Número do peticionamento_ no lug
feito

2020-11-07 00:03 UTC, LeoSilvaGomes commented on docs/evaluation/task_analysis/results.md
> +[4:33] Para conclusão do 1º fluxo que Micaella enfrentou, ele disse que foi tranquilo a tarefa, que "olhando direitinho" você pode encontrar o que precisa. Além disso, Micaella esclareceu uma de suas
muito obrigado pela dica, achei ótimo

2020-11-07 00:25 UTC, LeoSilvaGomes commented
Agora vai :tada:

2020-11-07 12:05 UTC, VictorJorgeFGA approved these changes

2020-11-09 12:07 UTC, merged