Avaliação do storyboard
Interacao-Humano-Computador/2020.1-SEI pull request #66
Opened 2020-11-04 20:07 UTC by LeoSilvaGomes

## Resolve (Issues)

#64 

## Tarefas gerais realizadas

- Descrever cada tópico dos dados coletados
- Fazer conclusão a partir dos dados coletados

2020-11-05 22:58 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +Neste documento reuniremos as pesquisas feitas para avaliar nosso storyboard para deixá-lo o mais fiel a realidade do [perfil de usuário](../../use_context/user_profiles.md) definido no projeto. Ness
* Adicionar crase em _"mais fiel a realidade do"_
* Na última frase, a palavra **refatorações** está escrita "**refatorões**"

2020-11-05 22:59 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +Este documento, apresentará dados coletados de um formulário com o intuito de mensurar a qualidade do storyboard. O formulário foi feito pelo [google forms](https://docs.google.com/forms/u/0/) e as p
Corrigir link pra _planning_.

2020-11-05 23:05 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +Inicialmente a ideia do grupo era fazermos entrevistas para validar o storyboard assim como feito para a análise de tarefas, porém percebemos que a análise de tarefas e o storyboard necessitam aborda
* Sugiro trocar a conjugação do verbo _fazermos_ para o infinitivo no começo da frase.
* Colocar uma vírgula depois de _storyboard_ no trecho "entrevistas para validar o storyboard assim como"
* A primeira frase está um pouco longa.

2020-11-05 23:07 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +O formulário é composto por 11 perguntas que começam com 3 perguntas de identificação da pessoa que está respondendo o formulário e continua avaliando se ouve utilização ou não do SEI, o formulário s
* Trocar a palavra _**ouve**_ por _**houve**_ no trecho _"e continua avaliando se ouve utilização ou não do SEI"_

2020-11-05 23:08 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +É importante lembrar que todos os voluntários que responderam o formulário foram informados da utilização de suas respostas, assim como alguns dados pessoais para compor essa avaliação. Todos os deta
Arrumar o link pro termo de consentimento.

2020-11-05 23:15 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +Para a avaliação ter resultados validos para a pesquisa, é verificado o embasamento que cada voluntário carrega sobre a plataforma. Desta forma, pode ser observado, que 75% dos voluntários utilizaram
* Colocar acento na palavra "validos".
* Acredito que a vírgula que vem após a palavra "observado" no trecho _"Desta forma, pode ser observado, que 75%", não está correta
* Faltou acento em "multiplas".

2020-11-05 23:23 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +A partir dos dados apresentados, se observa que 83,3% dos participantes já passaram por situações parecidas apresentadas no storyboard, o que nos confirma a tentativa positiva do storyboard ser o esp
* Trocar ["se observa" pra "observa-se"](https://educacao.uol.com.br/disciplinas/portugues/colocacao-pronominal-como-usar-os-pronomes-obliquos-atonos.htm) no trecho: _"A partir dos dados apresentados, se observa que 83,3% dos participantes"_

2020-11-05 23:26 UTC, VictorJorgeFGA commented on docs/evaluation/storyboard/results.md
> +| 28/10/2020 |  0.1   | Criação da introdução do documento de resulto do storyboard | Leonardo Gomes e João Zarbielli |
Faltou atualizar o histórico de versões. Também é necessário corrigir a palavra "resulto" pra "resultado"

2020-11-05 23:27 UTC, VictorJorgeFGA requested changes
Ficou ótimo. Parabéns!

2020-11-06 02:39 UTC, LeoSilvaGomes commented on docs/evaluation/storyboard/results.md
> +Neste documento reuniremos as pesquisas feitas para avaliar nosso storyboard para deixá-lo o mais fiel a realidade do [perfil de usuário](../../use_context/user_profiles.md) definido no projeto. Ness
feito, coloquei para https://sei.unb.br/sei/controlador_externo.php?acao=usuario_externo_logar&acao_origem=usuario_externo_logar&id_orgao_acesso_externo=0 esse link

2020-11-06 11:19 UTC, VictorJorgeFGA approved these changes

2020-11-09 12:07 UTC, merged